sudo: required

services: [docker]

env:
  matrix:
    - REPO=https://github.com/nextcloud/nextcloud-snap
    - REPO="https://github.com/elopio/juju -b snapcraft-gcc"

script:
  - git clone https://github.com/elopio/snapcraft
  - cd snapcraft
  - git checkout build_external_snaps
  - $TRAVIS_BUILD_DIR/snap-in-docker.sh $REPO
