sudo: required

services: [docker]

env:
  matrix:
    - REPO=https://github.com/nextcloud/nextcloud-snap
    - REPO=https://git.launchpad.net/~checkbox-dev/plainbox-provider-snappy/+git/packaging
    - REPO=https://github.com/maas/meta-maas
    - REPO=https://github.com/docker-snap/docker

script:
  - git clone https://github.com/elopio/snapcraft
  - cd snapcraft
  - git checkout build_external_snaps
  - $TRAVIS_BUILD_DIR/snap-in-docker.sh $REPO
