sudo: required

services: [docker]

env:
  matrix:
    - REPO=https://github.com/nextcloud/nextcloud-snap REPO_BRANCH=master
    - REPO=https://github.com/nextcloud/nextcloud-snap REPO_BRANCH=develop
    - REPO=https://git.launchpad.net/checkbox-snappy
    - REPO=https://github.com/maas/meta-maas
    - REPO=https://github.com/docker-snap/docker
    - REPO=https://github.com/magne4000/quassel-webserver
    - REPO=https://github.com/conjure-up/conjure-up
    - REPO=https://github.com/getnikola/nikola/
    - REPO=https://github.com/kyrofa/darktable-snap
    - REPO=https://github.com/kyrofa/ros-lunar-snap
    - REPO=https://github.com/lxc/lxd-pkg-ubuntu REPO_BRANCH=snappy-16
    - REPO=https://github.com/elopio/hashicorp-snaps REPO_BRANCH=master PPA=ppa:gophers/archive
    - REPO=https://github.com/mysql/mysql-snap REPO_BRANCH=5.7
    - REPO=https://github.com/mysql/mysql-snap REPO_BRANCH=8.0
    - REPO=https://github.com/heroku/cli
    - REPO=https://github.com/anbox/anbox/
    # Custom plugins and zulu-jre.
    - REPO=https://github.com/openhab/openhab-snap
    # Official kernel snaps.
    - REPO=https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-snap/+git/xenial REPO_BRANCH=pc
    - REPO=https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-snap/+git/xenial REPO_BRANCH=raspi2
    - REPO=https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-snap/+git/xenial REPO_BRANCH=snapdragon
    # System enablement snaps.
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/network-manager
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/bluez
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/alsa-utils
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-ap
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/upower
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/tpm
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/tpm2
    - REPO=https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/pulseaudio

script:
  - sudo apt update
  - sudo apt install --yes bzr git python3 python3-docopt snapd software-properties-common
  - export PATH=/snap/bin:$PATH
  - sudo snap install snapcraft --classic --edge
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository --yes PPA; fi
  - sudo ./setup_lxd.sh
  - git clone --progress $REPO repo
  - cd repo
  - if [ ! -z "$REPO_BRANCH" ]; then git checkout $REPO_BRANCH; fi
  - echo Building with snapcraft $(snapcraft --version) ...
  - snapcraft cleanbuild --debug

after_failure:
  # Run again, using the latest released snapcraft, to see if it's a regression.
  - sudo snap refresh snapcraft --stable
  - echo Building with snapcraft $(snapcraft --version) ...
  - snapcraft cleanbuild --debug
