sudo: required

services: [docker]

env:
  matrix:
    - REPO=https://github.com/nextcloud/nextcloud-snap
    - REPO=https://git.launchpad.net/~checkbox-dev/plainbox-provider-snappy/+git/packaging
    - REPO=https://github.com/maas/meta-maas
    - REPO=https://github.com/docker-snap/docker
    - REPO=https://github.com/magne4000/quassel-webserver
    - REPO=https://github.com/conjure-up/conjure-up
    - REPO=https://github.com/getnikola/nikola/
    - REPO=https://github.com/kyrofa/darktable-snap
    - REPO=https://github.com/lxc/lxd-pkg-ubuntu REPO_BRANCH=snappy-16

script:
  - git clone https://github.com/elopio/snapcraft
  - cd snapcraft
  - git checkout build_external_snaps
  - $TRAVIS_BUILD_DIR/snap-in-docker.sh $REPO $REPO_BRANCH
